### ISSUE TITLE
ability to do OpenSSL initialization outside of luacrypto

### ISSUE THREAD

**Issue by IlyaM** [mkottman/luacrypto#13]
Hi,

Is it possible to change the module so that OpenSSL environment initialization is conditionally disabled in luacrypto so that application which embeds Lua and luacrypto can do OpenSSL environment initialization by itself? By the initialization I mean calls OpenSSL_add_all_digests() and OpenSSL_add_all_ciphers() in luaopen_crypto(). This is necessary in certain use cases; particularly it is more or less required for multi-threaded applications where application creates multiple independent Lua environments in different threads where each Lua environment loads luacrypto library. The problem is that OpenSSL environment initialization should be done only once per-process; if you try to do OpenSSL enviroment initialization in multiple threads at the same time it causes crashes as corresponding API is not supposed to be called in parallel. Also in general for multi thread use case OpenSSL environment needs more complex initialization logic.

**Comment by mkottman** [comment]
Hi, that's a good idea, however I am thinking on how to implement this in such a way that existing code using this library is not affected. There are several possibilities:
- Add a function called init() which calls OpenSSL_add_all_digests() and OpenSSL_add_all_ciphers(). However, existing code would need to be changed and simple one-liners would need to be extended, something I want to avoid.
- Use an environment variable such as OPENSSL_INITIALIZED, which if set to anything, the module would not call the initialization functions.
- Detect if any digests/ciphers are available (something like: `if #crypto.list('digests') + #crypto.list('ciphers') == 0 then ... end`), and call the functions if no ciphers/digests are available.

Which do you think would be best?

**Comment by IlyaM** [comment]
```
- Add a function called init() which calls OpenSSL_add_all_digests() and OpenSSL_add_all_ciphers(). However, existing code would need to be changed and simple one-liners would need to be extended, something I want to avoid.
```

I don't like this option as well. For simple use cases luacrypto library should just work out of box.

```
- Use an environment variable such as OPENSSL_INITIALIZED, which if set to anything, the module would not call the initialization functions.
```

Not sure if I like this option. Normally environment variables are used to configure behavior of application by users and not configure behavior of library by application. Details of openssl initialization is application logic which shouldn't be configurable by user.

```
- Detect if any digests/ciphers are available (something like: `if #crypto.list('digests') + #crypto.list('ciphers') == 0 then ... end`), and call the functions if no ciphers/digests are available.
```

On the first glance it should work assuming that OpenSSL's internal table of digest algorithms and ciphers is expected to be completely empty without explicit initialization.

```
Which do you think would be best?
```

Another simple option is to make this behavior configurable at compile time. At least for me having simple #ifdef around OpenSSL_add_all_digests() and OpenSSL_add_all_ciphers() calls would work.

**Comment by mkottman** [comment]
> Another simple option is to make this behavior configurable at compile time. At least for me having simple #ifdef around OpenSSL_add_all_digests() and OpenSSL_add_all_ciphers() calls would work.

Okay, honestly I was only thinking of runtime options. Because this is so simple, I will add a compile flag that will add external initialization of OpenSSL.
