### ISSUE TITLE
How to install and use luacrypto in Lua-Corona application on Windows platform? Is this a valid combination? Please advise.

### ISSUE THREAD

**Issue by rajup3** [mkottman/luacrypto#21]

**Comment by mkottman** [comment]
AFAIK there is currently no way to all native API in Corona. See [this feature request](http://developer.anscamobile.com/forum/2010/09/12/native-api-access-and-custom-module-support).

**Comment by rajup3** [comment]
Hi Michal,

Many thanks for sharing feature request list in Corona, this is really helpful. It seems I need to look for Corona based solution for AES encryption. 
Thanks again.
